# Numpy

In [1]:
! pip install Numpy

In [11]:
import numpy as np
from numpy import *

In [12]:
x = 5
y = cos(x)
y

0.28366218546322625

In [13]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [18]:
b = np.array([[-3,4,6,3],
              [0,5,7,5],[0,8,9,6]])

b

array([[-3,  4,  6,  3],
       [ 0,  5,  7,  5],
       [ 0,  8,  9,  6]])

In [19]:
b.shape

(3, 4)

In [22]:
b[1,1]

5

In [27]:
b[:2]

array([[-3,  4,  6,  3],
       [ 0,  5,  7,  5]])

In [28]:
c = np.array([[1,2,2,3,3],[2,2,5,6,7],[3,8,9,7,5],[5,5,5,6,7],[-6,-9,8,2,3]])
c

array([[ 1,  2,  2,  3,  3],
       [ 2,  2,  5,  6,  7],
       [ 3,  8,  9,  7,  5],
       [ 5,  5,  5,  6,  7],
       [-6, -9,  8,  2,  3]])

In [30]:
c[1:3,2:5]

array([[5, 6, 7],
       [9, 7, 5]])

In [32]:
x = np.zeros([5,5])
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
x[1,2]= -5
x

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., -5.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [34]:
d = np.ones([5,5])
d

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
d[3,3]= 80

In [36]:
d

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1., 80.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [37]:
# Linspace and arange

In [39]:
x = np.linspace(0,10,11)
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [40]:
y = x**2
y

array([  0.,   1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.])

In [44]:
theta = np.linspace(0,360,10)
z = np.sin(theta*np.pi/180)

theta

array([  0.,  40.,  80., 120., 160., 200., 240., 280., 320., 360.])

In [47]:
# arange
x = np.arange(0,11,0.5)
x


array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5])

In [49]:
theta = np.arange(0,360+30,30)
theta

array([  0,  30,  60,  90, 120, 150, 180, 210, 240, 270, 300, 330, 360])

In [50]:
z = np.sin(theta*np.pi/180)

In [51]:
z

array([ 0.00000000e+00,  5.00000000e-01,  8.66025404e-01,  1.00000000e+00,
        8.66025404e-01,  5.00000000e-01,  1.22464680e-16, -5.00000000e-01,
       -8.66025404e-01, -1.00000000e+00, -8.66025404e-01, -5.00000000e-01,
       -2.44929360e-16])

In [52]:
m1 = np.array([[1,2,3],[2,5,6],[8,6,3]])
m2 = np.array([[2,3,8],[5,1,7],[0,0,5]])

m3 = m1+m2

In [53]:
m3

array([[ 3,  5, 11],
       [ 7,  6, 13],
       [ 8,  6,  8]])

In [54]:
m4 = np.dot(m1,m2)

In [55]:
m4

array([[ 12,   5,  37],
       [ 29,  11,  81],
       [ 46,  30, 121]])